### ISSUE TITLE
unexpected keyword argument 'exclude_samples'

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#108]
After installing the current `dev` branch I get this error running looper:

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 705, in main
    exclude_samples=args.exclude_protocols) as prj:
TypeError: __init__() got an unexpected keyword argument 'exclude_samples'
```

**Comment by nsheff** [comment]
Now I'm getting this error: is this a different issue?

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 703, in main
    with ProjectContext(prj, selector_attribute=args.selector_attribute, selector_include=args.selector_include,
AttributeError: 'Namespace' object has no attribute 'selector_attribute'
```

**Comment by nsheff** [comment]
solved be adding hook to selectors into the looper arg parser.

**Comment by nsheff** [comment]
but see: https://github.com/pepkit/peppy/issues/256
will require that to be fully functional at the looper level.
