### ISSUE TITLE
destroy error with compute

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#118]
running `looper destroy` yields:

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 705, in main
    prj.dcc.activate_package(args.compute)
AttributeError: 'Namespace' object has no attribute 'compute'
```

**Comment by nsheff** [comment]
because `compute` is only on the `run` subparser, not on `destroy`. why woul dyou need compute on destroy?
