### ISSUE TITLE
Exception for missing subproject

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#12]
Right now, specification of a subproject (with `--sp`) that isn't defined in the given project config file results in a `KeyError`. Once familiar with `looper`, it's likely not tricky to figure out the cause, but it could be nice for newer users to provide a different exception for this, or at least a clearer message than simply the name of the subproject, e.g. something like `KeyError: No subproject named '<sp>'` as the last line of the traceback.

**Comment by nsheff** [comment]
since looper is user-facing and not really going to be imported interactively by devs, I'd suggest not even raising an exception but just printing an error message (like your example) and then exiting with a nonzero value.

**Comment by vreuter** [comment]
I'm not sure what you mean by "imported interactively"--I just mean when doing something like `check` or `run` from the command line, but regardless, I think I agree. My first instinct was a different exception, but since there's no way/need to catch this really, I think it just makes sense to tailor a message to the underlying cause then exit. I don't see an alternate course of action in that case other than ignoring the subproject, but that could be particularly problematic in a case in which someone used something like a `micro` subproject with `run` itself, and then we instead fell back into using the base project with all of the samples.

**Comment by vreuter** [comment]
Anyway, that was sort of rambling, but yes, TLDR--I agree and think the message + exit is the way to go.

**Comment by nsheff** [comment]
by 'interactively' I meant within a python session. If it were going to be used interactively then an exception is relevant; if it's just a command-line interface you're talking about, you don't even need to worry about "a different exception" complexity; just print an error message and exit... that's all. If you want to implement with an exception that's fine, just no need to pass that on to the CLI user at all.

**Comment by vreuter** [comment]
It's gotten worse...we now just "disregard" the subproject:
```
Subproject 'missing' requested but no subprojects are defined. Disregarding
```

**Comment by vreuter** [comment]
OK, different behavior for none defined vs. some defined and an undefined one is selected.
Can we handle these the same way? I don't think it makes sense to differently treat the notion of _user requested undefined subproject_ based on whether or not any subprojects were defined.

I think in either case (request fails b/c no sp's are defined or request fails b/c no defined sp matches the request) should result in message-and exit. @nsheff ?

**Comment by vreuter** [comment]
```
Traceback (most recent call last):
  File "/home/vpr9v/venvs/py2/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/looper/looper.py", line 702, in main
    compute_env_file=getattr(args, 'env', None))
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/looper/project.py", line 36, in __init__
    no_compute_exception=RuntimeError, **kwargs)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/peppy/project.py", line 184, in __init__
    self.parse_config_file(subproject)
  File "/home/vpr9v/venvs/py2/local/lib/python2.7/site-packages/peppy/project.py", line 784, in parse_config_file
    subproject, ", ".join([sp for sp in config["subprojects"]])))
Exception: Unknown subproject (missing); defined subprojects: albatross, frog
```

**Comment by nsheff** [comment]
> I think in either case (request fails b/c no sp's are defined or request fails b/c no defined sp matches the request) should result in message-and exit. @nsheff ?

Agreed.

Instead of "Unknown subproject (missing)" How bout: Subproject "missing" not found; Defined subprojects:...
