### ISSUE TITLE
looper summarize bug with NoneType object

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#164]
```
create_object_html: cumulative_frip.html references nonexistent object files
create_object_html: fragment_distribution.html references nonexistent object files
Could not read the log file '/sfs/lustre/allocations/shefflab/processed//dura_macs/results_pipeline/Rag_f1/PEPATAC_log.md' with encodings '['utf-8', 'ascii']'
[2019-04-15 14:08:10,000] ERROR in caravel: Unhandled Exception: 'NoneType' object has no attribute 'drop_duplicates'
Traceback (most recent call last):
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel.py", line 90, in decorated
    return func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/caravel.py", line 383, in action
    run_looper(prj=globs.p, args=args, act=globs.act, log_path=globs.log_path, logging_lvl=globs.logging_lvl)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/helpers.py", line 334, in decorated
    func(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/helpers.py", line 367, in run_looper
    _render_summary_pages(prj)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/caravel/helpers.py", line 401, in _render_summary_pages
    footer=footer)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/html_reports.py", line 633, in create_index_html
    self.create_status_html(objs, navbar_reports, footer))
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/html_reports.py", line 465, in create_status_html
    t.drop_duplicates(subset=['value'], keep='last', inplace=True)
AttributeError: 'NoneType' object has no attribute 'drop_duplicates'
```

**Comment by michalstolarczyk** [comment]
this should resolve that, can you test it on that example @nsheff ?

**Comment by nsheff** [comment]
yep, it worked. great thanks.
