### ISSUE TITLE
error running looper on CLI with no args

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#186]
```
looper
Command: None (Looper version: 0.12.0)
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/looper/looper.py", line 804, in main
    determine_config_path(args.config_file), subproject=args.subproject,
AttributeError: 'Namespace' object has no attribute 'config_file'
```

**Comment by vreuter** [comment]
What would you like this to do?

**Comment by nsheff** [comment]
just show the help like it has done for awhile. I'm not sure what changed but it always just worked like normal

**Comment by vreuter** [comment]
You have a good memory! The no-arg run has produced an `AttributeError` rather than showing help in every version dating back at least through 0.9.1

**Comment by nsheff** [comment]
I guess it's been awhile since I tested it.
