### ISSUE TITLE
looper depends on pytest but it is not in requirements

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#190]
raised by @guertinlab

```
somC02TV103J1GQ:vcap guertinlab$ looper run vcap_example.yaml
Traceback (most recent call last):
  File "/usr/local/bin/looper", line 9, in <module>
    load_entry_point('loopercli==0.12.0', 'console_scripts', 'looper')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/loopercli-0.12.0-py2.7.egg/looper/__init__.py", line 12, in <module>
    from .conductor import SubmissionConductor
  File "/Library/Python/2.7/site-packages/loopercli-0.12.0-py2.7.egg/looper/conductor.py", line 11, in <module>
    from .utils import \
  File "/Library/Python/2.7/site-packages/loopercli-0.12.0-py2.7.egg/looper/utils.py", line 8, in <module>
    from peppy import \
  File "build/bdist.macosx-10.13-intel/egg/peppy/__init__.py", line 13, in <module>
  File "build/bdist.macosx-10.13-intel/egg/peppy/project.py", line 67, in <module>
  File "build/bdist.macosx-10.13-intel/egg/peppy/sample.py", line 20, in <module>
  File "build/bdist.macosx-10.13-intel/egg/peppy/utils.py", line 21, in <module>
  File "build/bdist.macosx-10.13-intel/egg/ubiquerg/__init__.py", line 3, in <module>
  File "build/bdist.macosx-10.13-intel/egg/ubiquerg/assistest.py", line 3, in <module>
ImportError: No module named pytest
```

if it is the case that looper really is requiring pytest, this should be fixed.

If it is not the case, then something is broken with version dependencies or something here...

**Comment by nsheff** [comment]
just to make it clear: `looper` should *not` rely on `pytest` being installed (so we should not add `pytest` to the requirements file to solve this)

**Comment by vreuter** [comment]
https://github.com/pepkit/ubiquerg/issues/2

**Comment by nsheff** [comment]
thanks, that's exactly what I needed
