### ISSUE TITLE
NameError: global name 'os' is not defined

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/looper#197]
This looks like a ngstk and looper incompatibility error.

The error is:
```
$ looper run HEK_TIR1_ZNF143AID.yaml -d
Command: run (Looper version: 0.12.2-dev)
Loading divvy config file: /sfs/lustre/scratch/jps3dp/tools/databio/uva_rivanna.yaml
Activating compute package 'default'
Reading sample annotations sheet: '/sfs/lustre/scratch/jps3dp/DATA/proseq/HEK_TIR1_ZNF143AID.csv'
Setting sample sheet from file '/sfs/lustre/scratch/jps3dp/DATA/proseq/HEK_TIR1_ZNF143AID.csv'
Finding pipelines for protocol(s): PROSEQ
Known protocols: PROSEQ, proseq, PRO, PRO-seq, PRO-SEQ, pro
## [1 of 1] HEK_TIR1_ZNF143AID_rep3 (PROSEQ)
Traceback (most recent call last):
  File "/home/jps3dp/.local/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/home/jps3dp/.local/lib/python2.7/site-packages/looper/looper.py", line 799, in main
    rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/looper/looper.py", line 402, in __call__
    curr_pl_fails = conductor.add_sample(sample, rerun=rerun)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/looper/conductor.py", line 203, in add_sample
    self.pl_iface, pipeline_name=self.pl_key)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/looper/sample.py", line 161, in set_pipeline_attributes
    self.input_file_size = get_file_size(self.all_inputs)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/ngstk/inspection.py", line 28, in get_file_size
    return float(sum([get_file_size(x) for x in filename]))
  File "/home/jps3dp/.local/lib/python2.7/site-packages/ngstk/inspection.py", line 31, in get_file_size
    for f in filename.split(" ") if f is not ''])
NameError: global name 'os' is not defined
```

The solution appears to be in modifying looper/sample.py to ensure `import os` is *before* any `from`s.
Before:
```
""" Extension of peppy.Sample to support looper-specific operations. """

from operator import itemgetter
import os
```
After:
```
""" Extension of peppy.Sample to support looper-specific operations. """

import os
from operator import itemgetter
```
Not entirely sure why that should be the case?

**Comment by vreuter** [comment]
Yeah that seems bizarre, but glad you found this. It'd be nice to know the root cause, but I'll make the change on `dev` in the meantime...
