### ISSUE TITLE
v0.7.2 introduces logger error

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#2]
``` 
looper --version
Traceback (most recent call last):
  File "/sfs/nfs/blue/ns5bc/.local/bin/looper", line 11, in <module>
    load_entry_point('looper==0.7.2', 'console_scripts', 'looper')()
  File "/apps/software/standard/core/anaconda2/4.4.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entr
y_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/apps/software/standard/core/anaconda2/4.4.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2598, in load_ent
ry_point
    return ep.load()
  File "/apps/software/standard/core/anaconda2/4.4.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2258, in load
    return self.resolve()
  File "/apps/software/standard/core/anaconda2/4.4.0/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 19, in <module>
    from .loodels import Project
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/loodels.py", line 3, in <module>
    from . import models
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/models.py", line 101, in <module>
    _LOGGER.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'
```

This is not an error in `v0.7.1`

**Comment by nsheff** [comment]
This turned out to be a local issue with my python package setup. I never figured out exactly what was wrong, but solved the problem by nuking all local python package installs and starting over.
