### ISSUE TITLE
Unknown error (after updating looper?)

### ISSUE THREAD

**Issue by rcorces** [pepkit/looper#200]
Honestly I have no idea why this is happening and its probably something stupid but I've been trying to figure it out for hours and havent made any progress. I recently updated looper so maybe that has something to do with it.
```
[mcorces@sh-ln07 login /oak/stanford/groups/howchang/users/mcorces/Brain_All/alignments]$ looper run --compute all ./config/190619_BrainControls_config.yaml 
Command: run (Looper version: 0.12.0)
Loading divvy config file: /share/PI/howchang/users/mcorces/tools/pepenv/stanford.yaml
Activating compute package 'default'
Setting sample sheet from file '/oak/stanford/groups/howchang/users/mcorces/Brain_All/alignments/config/190619_BrainControls_annotation.csv'
Cannot correctly format data source (KeyError): 'sample_name' -- /oak/stanford/groups/howchang/users/mcorces/Brain_All/fastq/{sample_name}*R1*.fastq.gz
Cannot correctly format data source (KeyError): 'sample_name' -- /oak/stanford/groups/howchang/users/mcorces/Brain_All/fastq/{sample_name}*R2*.fastq.gz
Cannot correctly format data source (KeyError): 'sample_name' -- /oak/stanford/groups/howchang/users/mcorces/Brain_All/fastq/{sample_name}*R1*.fastq.gz
Cannot correctly format data source (KeyError): 'sample_name' -- /oak/stanford/groups/howchang/users/mcorces/Brain_All/fastq/{sample_name}*R2*.fastq.gz
Activating compute package 'all'
Traceback (most recent call last):
  File "/share/PI/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/looper/looper.py", line 827, in main
    rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/looper/looper.py", line 290, in __call__
    if not self.prj.interfaces:
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/peppy/project.py", line 117, in __getattr__
    return getattr(self.prj, item)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 17, in __getattribute__
    res = super(PathExAttMap, self).__getattribute__(item)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/looper/project.py", line 52, in interfaces
    return copy.deepcopy(self._interfaces)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
TypeError: __init__() missing 1 required positional argument: 'config'
```

annotation and config files attached (and thus converted to txt in order to upload).
What am I missing?
[190619_BrainControls_annotation.txt](https://github.com/pepkit/looper/files/3312601/190619_BrainControls_annotation.txt)
[190619_BrainControls_config.txt](https://github.com/pepkit/looper/files/3312602/190619_BrainControls_config.txt)

**Comment by nsheff** [comment]
I'm guessing you *might* be being bitten by a decision to remove the `sample_name` access in [peppy version 0.21](http://peppy.databio.org/en/latest/changelog/), which was restored a month later in version 0.22...

you can try updating peppy (`pip install --user --upgrade peppy`) and see if that solves it... 

On my machine your files are working correctly, so I actually this is not your problem and is ours...

if the peppy update doesn't solve it, try updating looper again to 0.12.2 (the latest release)

**Comment by vreuter** [comment]
Yeah definitely looks possible from the traceback, and that this is `loopercli` 0.12.0

**Comment by rcorces** [comment]
This was what I needed! thank you!
I had updated looper using `pip --upgrade` but I needed to use the `pip install --user --upgrade https://github.com/pepkit/looper/zipball/master` to get to the correct version (i think?). Then I also had to upgrade peppy as you mentioned. Is loopercli a new thing? I noticed that in the docs but didnt understand what it was. I actually did `pip uninstall looper` and then re-installed using the github link.

Lastly - and this might be important - I had to upgrade ngstk to 0.0.1rc2 from 0.0.1rc1.
Prior to doing that I got this - 
```
[mcorces@sh-104-35 /oak/stanford/groups/howchang/users/mcorces/Brain_All/alignments]$ looper run --ignore-flags --compute all ./config/190619_BrainControls_config.yaml 
Command: run (Looper version: 0.12.2)
Loading divvy config file: /share/PI/howchang/users/mcorces/tools/pepenv/stanford_divvy.yaml
Activating compute package 'default'
Reading sample annotations sheet: '/oak/stanford/groups/howchang/users/mcorces/Brain_All/alignments/config/190619_BrainControls_annotation.csv'
Setting sample sheet from file '/oak/stanford/groups/howchang/users/mcorces/Brain_All/alignments/config/190619_BrainControls_annotation.csv'
Activating compute package 'all'
Finding pipelines for protocol(s): ATAC
Known protocols: ATAC, ATAC-SEQ
## [1 of 2] RCLN-HIPP-14-0941-X004-S07-L038-B1-T2-P009 (ATAC)
Traceback (most recent call last):
  File "/share/PI/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/looper/looper.py", line 798, in main
    rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/looper/looper.py", line 400, in __call__
    curr_pl_fails = conductor.add_sample(sample, rerun=rerun)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/looper/conductor.py", line 203, in add_sample
    self.pl_iface, pipeline_name=self.pl_key)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/looper/sample.py", line 161, in set_pipeline_attributes
    self.input_file_size = get_file_size(self.all_inputs)
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/ngstk/inspection.py", line 28, in get_file_size
    return float(sum([get_file_size(x) for x in filename]))
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/ngstk/inspection.py", line 28, in <listcomp>
    return float(sum([get_file_size(x) for x in filename]))
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/ngstk/inspection.py", line 31, in get_file_size
    for f in filename.split(" ") if f is not ''])
  File "/home/groups/howchang/users/mcorces/tools/python/virtualenv/python-3.6.1/lib/python3.6/site-packages/ngstk/inspection.py", line 31, in <listcomp>
    for f in filename.split(" ") if f is not ''])
NameError: name 'os' is not defined
```

**Comment by rcorces** [comment]
As an aside, its a bit confusing to me why the looper output shows two instances of "activating compute package"
```
Command: run (Looper version: 0.12.2)
Loading divvy config file: /share/PI/howchang/users/mcorces/tools/pepenv/stanford_divvy.yaml
Activating compute package 'default'
Reading sample annotations sheet: '/oak/stanford/groups/howchang/users/mcorces/Brain_All/alignments/config/190619_BrainControls_annotation.csv'
Setting sample sheet from file '/oak/stanford/groups/howchang/users/mcorces/Brain_All/alignments/config/190619_BrainControls_annotation.csv'
Activating compute package 'all'
```
From the docs it seems like this divvy thing is new so maybe this is just part of some transition?

Anyways, closing this because you solved my problem. Thanks again!

**Comment by vreuter** [comment]
Interesting re: the `os` issue -- @nsheff this is also what @jpsmith5 reported elsewhere but was solved differently?

**Comment by nsheff** [comment]
> Is loopercli a new thing?

relatively -- basically, we now put looper on PyPI, so you can install it with `pip install --user loopercli`. The name `'looper` was taken and I wasn't able to get it. It just saves you from having to install it with github.

If you had just done: `pip install --user --upgrade loopercli`, it would have upgraded both looper and peppy for you and you would have been done. So, going forward in the future, that's all you need to do to get the latest release version. You should only have to go to the github link route if you want to get the dev version.

**Comment by nsheff** [comment]
> As an aside, its a bit confusing to me why the looper output shows two instances of "activating compute package"

Divvy first activates the default compute package, and then activates the one you specify, which really updates it (so it adds to it). I agree I should probably just not show that for the default one... so I've taken it out now. thanks.

**Comment by nsheff** [comment]
> NameError: name 'os' is not defined

> Interesting re: the os issue -- @nsheff this is also what @jpsmith5 reported in #197 but was solved differently?

Looks similar, huh... do you think it has something to do with circular dependencies or multiple imports or something? I wonder if import order in packages is relevant when there's multiple things relying on multiple other things....

another thought: right now do we still have 2 ngstk modules? the standalone one and one in pypiper, right? Could there be some conflict there? I don't really know the status of this division...

**Comment by nsheff** [comment]
> From the docs it seems like this divvy thing is new so maybe this is just part of some transition?

Yeah we launched the divvy thing in april. Basically, it just standardized and made more modular the earlier 'pepenv' concept. Now you could use this same configuration with other tools.

take a glance at the [divvy docs](http://divvy.databio.org/en/latest/) to see what I mean. For example, you can now change these settings in caravel really easily. You could also use them for totally unrelated stuff because divvy is a fully-functional CLI in its own right. I think it's a pretty flexible system.

let me know if you have any other feedback into how this works.

**Comment by vreuter** [comment]
> > NameError: name 'os' is not defined
> 
> > Interesting re: the os issue -- @nsheff this is also what @jpsmith5 reported in #197 but was solved differently?
> 
> Looks similar, huh... do you think it has something to do with circular dependencies or multiple imports or something? I wonder if import order in packages is relevant when there's multiple things relying on multiple other things....
> 
> another thought: right now do we still have 2 ngstk modules? the standalone one and one in pypiper, right? Could there be some conflict there? I don't really know the status of this division...

Yeah, nothing new's going into `ngstk` right now and hasn't in a while after an initial burst or two, primarily motivated by things in `peppy` I think rather than anything in `pypiper`. I'm sort of curious about the ordering of the imports and why that seems to affect things, but not enough to really dig at it unless it continues to come up in other places.

**Comment by nsheff** [comment]
>  nothing new's going into ngstk right now  

which ngstk? the standalone one is not even used in peppy anymore, right? I don't quite follow...

**Comment by vreuter** [comment]
> > nothing new's going into ngstk right now
> 
> which ngstk? the standalone one is not even used in peppy anymore, right? I don't quite follow...

I meant the package (i.e., I'm not seeking to migrate anything at the moment). I'm not sure if anything new's gone into the `pypiper` one.
