### ISSUE TITLE
bug in file size calculation

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#239]
if a sample has more than 1 input file, then it now has a list, which when passed to os.stat is failing:

```
## [12 of 17] ATAC-seq_Adherent_rep1 (ATAC)
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 845, in main
    **compute_kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 430, in __call__
    curr_pl_fails = conductor.add_sample(sample, rerun=rerun)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 196, in add_sample
    sample.validate_inputs(schema=schema_source)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/sample.py", line 205, in validate_inputs
    for f in self.all_inputs if f != ""])/(1024 ** 3)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/sample.py", line 205, in <listcomp>
    for f in self.all_inputs if f != ""])/(1024 ** 3)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/ubiquerg/files.py", line 38, in size
    if os.path.isfile(path):
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
```

Reproduce with:

```
DIVCFG=/project/shefflab/rivanna_config/divcfg/uva_rivanna_adapters.yaml looper run paqc.yaml --amendments sra_convert -d 
```

I think all the samples work until one that has a subsample with multiple SRR files in there, which must be getting passed on as a list instead of a path.

**Comment by nsheff** [comment]
we should add this case in as a smoketest

**Comment by nsheff** [comment]
The dev version of ubqiuerg solves this by allowing `size()` to take either a path or a list of paths.

@stolarczyk do you think it should be solved differently?

**Comment by stolarczyk** [comment]
I can confirm `dev` ubiquerg solves that.
