### ISSUE TITLE
NameError: name 'project' is not defined

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#240]
Updated looper, divvy, peppy:

```
databio/lab| ~/code/paqc$ looper run paqc.yaml --amendments sra_convert --lump 25
Command: run (Looper version: 0.12.6-dev)
Using amendments: sra_convert
Finding pipelines for protocol(s): ATAC
Known protocols: *
## [1 of 17] GSM4289908 (ATAC)
## [2 of 17] GSM4196904 (ATAC)
## [3 of 17] GSM4196905 (ATAC)
## [4 of 17] GSM4317807 (ATAC)
## [5 of 17] GSM4310126 (ATAC)
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 845, in main
    **compute_kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 430, in __call__
    curr_pl_fails = conductor.add_sample(sample, rerun=rerun)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 226, in add_sample
    self.submit()
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 277, in submit
    script = self.write_script(self._pool, self._curr_size)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 419, in write_script
    self.pl_key, size, namespaces)  # piface < config
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/pipeline_interface.py", line 254, in choose_resource_package
    if COMPUTE_KEY in project[CONFIG_KEY][LOOPER_KEY] \
NameError: name 'project' is not defined
```

**Comment by nsheff** [comment]
Works.
