### ISSUE TITLE
NameError: name 'read_schema' is not defined

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#241]
```
looper run paqc.yaml --amendments sra_convert --lump 25
Command: run (Looper version: 0.12.6-dev)
Using amendments: sra_convert
Mismatch between derived attributes and sources. Lengths: 3!=4
Finding pipelines for protocol(s): ATAC
Known protocols: *
## [1 of 17] GSM4289908 (ATAC)
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 845, in main
    **compute_kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 430, in __call__
    curr_pl_fails = conductor.add_sample(sample, rerun=rerun)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 199, in add_sample
    sample.validate_inputs(schema=schema_dict)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/peppy/sample.py", line 193, in validate_inputs
    schema_dict = read_schema(schema=schema)
NameError: name 'read_schema' is not defined
```

This is a strange one -- I got this, but then it went away when  I installed eido. Then, I installed the latest peppy and it came back again.

I think maybe peppy is still trying to validate, even though that's been removed to eido...

**Comment by stolarczyk** [comment]
oops, I did not push peppy changes I made locally. Try reinstalling peppy and rerun

**Comment by nsheff** [comment]
Yes. Now just running into that other one again.
