### ISSUE TITLE
Error messaging for missing property is *too* verbose

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/looper#250]
All of the following is printed when really just **"jsonschema.exceptions.ValidationError: 'read1' is a required property"** is the relevant messaging...Actually, the message is so long I can't share it in the body...So here's a snippet.

Example:
```
looper run GSM4467115.yaml -d
Looper version: 0.12.6-dev
Command: run
Traceback (most recent call last):
  File "/home/jps3dp/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/jps3dp/.local/lib/python3.6/site-packages/looper/looper.py", line 757, in main
    **compute_kwargs)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/looper/looper.py", line 357, in __call__
    for schema_file in self.prj.get_schemas(sample_pifaces)]
  File "/home/jps3dp/.local/lib/python3.6/site-packages/looper/looper.py", line 357, in <listcomp>
    for schema_file in self.prj.get_schemas(sample_pifaces)]
  File "/home/jps3dp/.local/lib/python3.6/site-packages/eido/eido.py", line 161, in validate_sample
    _validate_object(sample_dict, sample_schema_dict, exclude_case)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/eido/eido.py", line 127, in _validate_object
    raise e
  File "/home/jps3dp/.local/lib/python3.6/site-packages/eido/eido.py", line 124, in _validate_object
    jsonschema.validate(object, schema)
  File "/home/jps3dp/.local/lib/python3.6/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'read1' is a required property

Failed validating 'required' in schema:
    {'input_attrs': ['read1', 'read2'],
     'properties': {'genome': {'anyOf': [{'description': 'Refgenie genome '
                                                         'registry '
                                                         'identifier',
                                          'type': 'string'},
                                         {'items': {'description': 'Refgenie '
                                                                   'genome '
                                                                   'registry '
                                                                   'identifier',
                                                    'type': 'string'},
                                          'type': 'array'}]},
                    'organism': {'anyOf': [{'description': 'Organism',
                                            'type': 'string'},
                                           {'items': {'description': 'Organism',
                                                      'type': 'string'},
                                            'type': 'array'}]},
                    'protocol': {'anyOf': [{'description': 'Must be an '
                                                           'ATAC-seq or '
                                                           'DNAse-seq '
                                                           'sample',
                                            'enum': ['ATAC',
                                                     'ATAC-SEQ',
                                                     'ATAC-seq',
                                                     'DNase',
                                                     'DNase-seq'],
                                            'type': 'string'},
                                           {'items': {'description': 'Must '
                                                                     'be '
                                                                     'an '
                                                                     'ATAC-seq '
```

**Comment by stolarczyk** [comment]
Agreed. `eido` has an option to make the error messages more digestable
