### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#261]
I'm not sure what's causing this error message; can't trace it:
from [this repo](https://github.com/databio/glass_aml_rrbs)

`looper run -d -l 1`

```
DEBU 10:26:27 | divvy.compute:compute:76 > Establishing project compute settings 
DEBU 10:26:27 | divvy.compute:compute:148 > Activating compute package 'default' 
DEBU 10:26:27 | divvy.compute:compute:155 > Creating Project compute 
DEBU 10:26:27 | divvy.compute:compute:157 > Adding entries for package_name 'default' 
DEBU 10:26:27 | divvy.compute:compute:175 > Submit template set to: /project/shefflab/rivanna_config/divcfg/templates/slurm_template.sub 
DEBU 10:26:27 | looper.project:project:120 > Ensuring project directories exist 
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 765, in main
    **{attr: getattr(args, attr) for attr in CLI_PROJ_ATTRS})
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/project.py", line 121, in __init__
    self.make_project_dirs()
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/project.py", line 235, in make_project_dirs
    folder_path = getattr(self, folder_key)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/attmap/pathex_attmap.py", line 17, in __getattribute__
    res = super(PathExAttMap, self).__getattribute__(item)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/project.py", line 205, in results_folder
    default="results_pipeline")
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/project.py", line 228, in _out_subdir_path
    getattr(self[EXTRA_KEY], key) or default)
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by stolarczyk** [comment]
after recent changes to the process of enrichment of CLI arguments with `Project.looper` data some code stills needs adjustments.

Im presume this issue should emerge only in non-dry run mode, when the project directories are created
