### ISSUE TITLE
Paths section should not be required

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#293]
Related to #285 

Should the new `paths` section be required?

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 10, in <module>
    sys.exit(main())
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 743, in main
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/looper.py", line 351, in __call__
    curr_pl_fails = cndtr.add_sample(sample, rerun=rerun)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 294, in add_sample
    self.submit()
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 352, in submit
    script = self.write_script(self._pool, self._curr_size)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/conductor.py", line 526, in write_script
    self.pl_iface.render_paths(namespaces=namespaces)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/looper/pipeline_interface.py", line 75, in render_paths
    raise AttributeError(f"'{PATHS_KEY}' section not found in the "
AttributeError: 'paths' section not found in the PipelineInterface object.
```

**Comment by nsheff** [comment]
I tried to put in `paths: null` and got: 

```
Ignoring invalid pipeline interface source: /sfs/qumulo/qproject/shefflab/deploy/plantref/plantref/pipeline_interfaces/wget_piface.
yaml. Caught exception: None is not of type 'object'
```

**Comment by nsheff** [comment]
it works if I do:

```
paths:
  dummy: dummy
```

So I think the paths should not be required.

**Comment by stolarczyk** [comment]
Ah ok I forgot that the command_template can just specify a command that's not necessarily sourced from paths.

**Comment by nsheff** [comment]
yeah, like `refgenie build`
