### ISSUE TITLE
looper 1.4.0 is incompatible with peppy 0.32.0

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#337]
```
looper --help
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 5, in <module>
    from looper.__main__ import main
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/__init__.py", line 23, in <module>
    from .conductor import (
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/conductor.py", line 17, in <module>
    from peppy.exceptions import RemoteYAMLError
ImportError: cannot import name 'RemoteYAMLError' from 'peppy.exceptions' (/home/nsheff/.local/lib/python3.8/site-packages/peppy/exceptions.py)
```

**Comment by nsheff** [comment]
See: https://github.com/pepkit/peppy/pull/367

**Comment by nsheff** [comment]
False alarm. I hadn't actually installed 0.32.0, apparently.
