### ISSUE TITLE
New sample table index variables in config file

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#338]
@stolarczyk The changelog for `0.32.0` says: 

```
- new project attributes:
  - `sample_table_index`
  - `subsample_table_index`
```

This isn't really documented anywhere, but I think these are intended to be parallel to `sample_table` and `subsample_table` in the PEP project_config specification, and define the column name to be used for the identifier attribute. Am I right?

This seems to be sort of working, but with looper I get this error:

```
looper run
No project config defined, using: /home/nsheff/code/pephub.databio.org/peps/nfcore/demo_rna/project_config.yaml. Read from dotfile (/home/nsheff/code/pephub.databio.org/peps/nfcore/demo_rna/.looper.yaml).
Looper version: 1.4.0
Command: run
Found 2 samples with non-unique names: {'RAP1_UNINDUCED_REP2', 'WT_REP1'}. Attempting to auto-merge.
Traceback (most recent call last):
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/ordattmap.py", line 46, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'sample_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 1065, in main
    p = Project(
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 106, in __init__
    self._samples_by_interface = self._samples_by_piface(self.piface_key)
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 690, in _samples_by_piface
    samples_by_piface[source].add(sample[SAMPLE_NAME_ATTR])
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 59, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/ordattmap.py", line 48, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/nsheff/.local/lib/python3.8/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'sample_name'
```

I guess this is likely a looper bug, and not a peppy bug, right? It seems just that looper isn't adapted to use this new model?

Also this will, really, require an update to to the specification. For now we could mark it as experimental.

**Comment by nsheff** [comment]
that makes perfect sense, thanks! Very helpful.

**Comment by ayobi** [comment]
Was able to replace `SAMPLE_NAME_ATTR` with `Project.sample_table_index` for a few like:

https://github.com/pepkit/looper/blob/df535be2a0bd7257ee37148cb601d688ec557909/looper/conductor.py#L54-L63

But for other's like the one below, I receive a dictionary key error:
https://github.com/pepkit/looper/blob/df535be2a0bd7257ee37148cb601d688ec557909/looper/conductor.py#L395-L397

`looper run project/project_config.yaml
Looper version: 1.4.0
Command: run
Using default config. No config found in env var: ['DIVCFG']
Pipestat compatible: False
Traceback (most recent call last):
  File "/home/aaronobrien/projects/looper/.venv/lib/python3.10/site-packages/attmap/ordattmap.py", line 46, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: <property object at 0x7fe62ae222a0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aaronobrien/projects/looper/.venv/bin/looper", line 33, in <module>
    sys.exit(load_entry_point('looper==1.4.0', 'console_scripts', 'looper')())
  File "/home/aaronobrien/projects/looper/.venv/lib/python3.10/site-packages/looper/looper.py", line 1098, in main
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/aaronobrien/projects/looper/.venv/lib/python3.10/site-packages/looper/looper.py", line 449, in __call__
    sample_pifaces = self.prj.get_sample_piface(sample[peppyProject.sample_table_index])
  File "/home/aaronobrien/projects/looper/.venv/lib/python3.10/site-packages/attmap/pathex_attmap.py", line 59, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/aaronobrien/projects/looper/.venv/lib/python3.10/site-packages/attmap/ordattmap.py", line 48, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/aaronobrien/projects/looper/.venv/lib/python3.10/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: <property object at 0x7fe62ae222a0>`

I'll keep digging to see why. Reading more about `sample_table_index` its supposed to default to `sample_name` so maybe what's happening is something in the code in passing in something different and therefore not recognizable. 

https://github.com/pepkit/peppy/blob/8449635bb35e16748e693bdd2c4820502d7b448d/peppy/project.py#L1102-L1119

**Comment by ayobi** [comment]
I was able to figure it out. I will PR and commit for review.
