### ISSUE TITLE
AttributeError: 'Project' object has no attribute '_config'

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#398]
Here's another cryptic error message, which I'm not sure what the problem is.

```
looper check
No project config defined (peppy), using: {'config_file': 'test_config.yaml', 'output_dir': '/home/nsheff/dnameth', 'sample_pipeline_interfaces': '../piface_rrbs.yaml', 'project_pipeline_interfaces': None}. Read from dotfile (/home/nsheff/code/dnameth_pipelines/examples/.looper.yaml).
Looper version: 1.5.2-dev
Command: check
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Not all environment variables were populated in derived attribute source: $CODE/microtest/data/{filename}
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/looper.py", line 1125, in main
    p = Project(
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 114, in __init__
    self.set_sample_piface(kwargs.get(SAMPLE_PL_ARG))
  File "/home/nsheff/.local/lib/python3.8/site-packages/looper/project.py", line 704, in set_sample_piface
    self._config.setdefault("sample_modifiers", {})
AttributeError: 'Project' object has no attribute '_config'
```

**Comment by donaldcampbelljr** [comment]
I believe this may no longer be an issue.
