### ISSUE TITLE
Not submitted: pipeline interface is missing 'command_extra' section

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#402]
Just recording some notes since I'm in the middle of trying to solve a looper issue:

I'm getting this error in the pytests, which I can reproduce with I think any try to looper run something:

```
> Not submitted: pipeline interface is missing 'command_extra' section
```

The source of the error is that looper automatically adds a `{sample.command_extra}` reference to the template, which it uses for populating extra commands, and then when jinja tries to get this from the sample object, it raises an error.

in the past, trying to retrieve a column from a sample that didn't exist would just return `None`, I think, but with removing attmap, now it's giving a `KeyError`. this being caught by looper and giving an erroneous error message.

if you change conductor.py line 745 to `raise e`, you see:

```
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/looper.py", line 1157, in main
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/looper.py", line 499, in __call__
    curr_pl_fails = cndtr.add_sample(sample, rerun=rerun)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/conductor.py", line 473, in add_sample
    self.submit()
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/conductor.py", line 510, in submit
    script = self.write_script(self._pool, self._curr_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/conductor.py", line 746, in write_script
    raise e
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/conductor.py", line 740, in write_script
    argstring = jinja_render_template_strictly(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.11/site-packages/looper/utils.py", line 206, in jinja_render_template_strictly
    rendered = templ_obj.render(**namespaces)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/nsheff/.local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 2, in top-level template code
  File "/home/nsheff/.local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.11/site-packages/peppy/simple_attr_map.py", line 44, in __getattr__
    return self._mapped_attr[item]
           ~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'command_extra'
```

I can solve this by adding this to the peppy.Sample object:

```
    @property
    def command_extra(self):
        """
        Get the command extra attribute

        :return str: command extra attribute
        """
        if "command_extra" not in self:
            return None
        return self["command_extra"]
```

but, I don't want to do that. so I need to figure out how to make looper not require these extra things, or add them to sample objects within looper.

Ideas for solution: 

an alternative that is more general is to update the new peppy simple attmap with:

```
    def __getattr__(self, item):
        try:
            return self._mapped_attr[item]
        except KeyError:
            return None
```

that's a more general solution... not 100% sure that's the right long-term solution, though.

**Comment by donaldcampbelljr** [comment]
We are currently doing something similar for the Looper Project:

```
  def __getattr__(self, item):
      """Samples are context-specific; other requests are handled
      locally or dispatched to Project."""
      if item == "samples":
          return fetch_samples(
              prj=self.prj,
              selector_attribute=self.attribute,
              selector_include=self.include,
              selector_exclude=self.exclude,
          )
      if item in ["prj", "include", "exclude"]:
          # Attributes requests that this context/wrapper handles
          return self.__dict__[item]
      else:
          # Dispatch attribute request to Project.
          if hasattr(self.prj, item):
              return getattr(self.prj, item)
          else:
              return self.prj.get(item)
```

Specifically `return self.prj.get(item)` is from class Mapping(Collection):

```
    def get(self, key, default=None):
        'D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.'
        try:
            return self[key]
        except KeyError:
            return default
```

**Comment by donaldcampbelljr** [comment]
I'm not sure I'm on the right path for replicating this, but so far, I attempt to access a sample attribute that does not exist (via the pipeline interface):

```
pipeline_name: count_lines
pipeline_type: sample
var_templates:
  pipeline: '{looper.piface_dir}/count_lines.sh'
command_template: >
  {pipeline.var_templates.pipeline} {sample.file} {sample.something_that_doesnt_exist}
```

And I see this error in the console:
```
/home/drc/GITHUB/looper/master/looper/venv/bin/python -m looper run --looper-config .looper.yaml --dry-run 
Looper version: 1.7.0
Command: run
Using default divvy config. You may specify in env var: ['DIVCFG']

Pipestat compatible: False
## [1 of 2] sample: frog_1; pipeline: count_lines
Error populating command template: 'peppy.sample.Sample object' has no attribute 'something_that_doesnt_exist'
> Not submitted: 'peppy.sample.Sample object' has no attribute 'something_that_doesnt_exist'
```

**Comment by nsheff** [comment]
I think we want to keep that behavior. I'm thinking now the best thing to do would be maybe one of these:

1. only add the `{sample.command_extra}` to the template *if command_extra is defined on the sample*. 
2. Have looper add `command_extra` = "" for any samples that don't already have it.

The problem with solution 1 is that  I think the command template is produced for the project, once; so we don't really want to modulate the template at the level of each sample, it's too much work.

So I think I favor the second solution.

The advantage is then you keep the above error, which is useful. If we did a more general solution like I suggest above, it would make that *not* an error, because those would just return blanks, which I think is bad..

**Comment by nsheff** [comment]
It turns out we're already doing solution 1.

I think I may have misinterpreted the original error; it says "pipeline interface" is missing the command_extra section. That's strange.

In any case, this no longer seems to be an issue.
