### ISSUE TITLE
html builder error

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#42]
```
Execution halted
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    load_entry_point('looper==0.9.0', 'console_scripts', 'looper')()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 866, in main
    Summarizer(prj)()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 673, in __call__
    report_builder = HTMLReportBuilder(self.prj)
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/html_reports.py", line 583, in __init__
    super(HTMLReportBuilder, self).__init__()
TypeError: super() argument 1 must be type, not classobj
```

not sure if this is the one addressed earlier...

**Comment by nsheff** [comment]
this is resolved in the `dev` branch.
