### ISSUE TITLE
pipeline interface keyerror message

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#45]
if a protocol has no mapping, `looper summarize` gives this error:

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    load_entry_point('looper==0.9.0', 'console_scripts', 'looper')()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 866, in main
    Summarizer(prj)()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 658, in __call__
    ifaces = self.prj.interfaces_by_protocol[alpha_cased(protocol)]
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/peppy/attribute_dict.py", line 163, in __getitem__
    raise KeyError(item)
KeyError: 'OTHER'
```

this should be made more informative.

**Comment by nsheff** [comment]
Maybe easy to fix along with #57?
