### ISSUE TITLE
KeyError: '_cli_extra' when calling looper run

### ISSUE THREAD

**Issue by joseverdezoto** [pepkit/looper#497]
I'm having an issue when I call `looper run` pointing to my config file. This is the error message I get:
```
looper run ./metadata/multi_study_pep/sraconvert_config.yaml
Looper version: 1.4.1
Command: run
Traceback (most recent call last):
  File "/cluster/home/verdezotom/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/cluster/home/verdezotom/.local/lib/python3.9/site-packages/looper/looper.py", line 1087, in main
    p = Project(
  File "/cluster/home/verdezotom/.local/lib/python3.9/site-packages/looper/project.py", line 105, in __init__
    setattr(self[EXTRA_KEY], attr_name, kwargs[attr_name])
  File "/cluster/home/verdezotom/.local/lib/python3.9/site-packages/peppy/project.py", line 1456, in __getitem__
    return self._project_data[item]
KeyError: '_cli_extra'
```

Is this related to something on my config file or maybe the sample table?

Thanks!

**Comment by donaldcampbelljr** [comment]
Are you able to update to the newest versions of Peppy and Looper and try those as a quick fix?

**Comment by khoroshevskyi** [comment]
Also, could you provide us with your config file?

**Comment by donaldcampbelljr** [comment]
@joseverdezoto Any update on this? Or shall I close the issue?

**Comment by donaldcampbelljr** [comment]
I will close for now. Please re-open if this is still an issue.
