### ISSUE TITLE
divvy list error

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#512]
I can't seem to `divvy list` on a fresh install of looper 2.0.0a1:

```
divvy list
Using divvy config: /home/nsheff/Dropbox/env/divvy_config/vole.yaml
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/divvy", line 8, in <module>
    sys.exit(divvy_main())
             ^^^^^^^^^^^^
  File "/home/nsheff/.local/share/pipx/venvs/looper/lib/python3.12/site-packages/looper/cli_divvy.py", line 129, in main
    dcc = ComputingConfiguration(filepath=divcfg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ComputingConfiguration.__init__() got an unexpected keyword argument 'filepath'
```

**Comment by donaldcampbelljr** [comment]
Ok, this should now be fixed in dev.
