### ISSUE TITLE
Improve error message for bad looper config

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#515]
The `looper init`  constructed a bad looper config (see #514), which looks like this.

```
cat .looper.yaml 
pep_config: metadata/sample_table.csv
output_dir: results
pipeline_interfaces:
- - pipeline/pipeline_interface.yaml
```

When I try to run a looper command, like `looper run`, I would expect it would say something like "Looper config is not formatted correctly" so that I know where to look for the error. Instead, I get this error:

```
looper run
Looper version: 2.0.0a1
Command: run
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/cli_pydantic.py", line 352, in main
    return run_looper(args, parser, test_args=test_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/cli_pydantic.py", line 158, in run_looper
    looper_config_dict = read_looper_dotfile()
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/utils.py", line 527, in read_looper_dotfile
    return read_looper_config_file(looper_config_path=dot_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/utils.py", line 807, in read_looper_config_file
    pipeline_types, piface_path = determine_pipeline_type(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/utils.py", line 733, in determine_pipeline_type
    piface_path = expandpath(piface_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/ubiquerg/paths.py", line 21, in expandpath
    return os.path.expandvars(os.path.expanduser(path))
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 259, in expanduser
TypeError: expected str, bytes or os.PathLike object, not list
```

**Comment by nsheff** [comment]
Can you also check the messaging for other possible common mistakes, like:

- what if the pipeline interface is malformed?
- what if pipeline interface is missing?
- what if the PEP is malformed?
- what if PEP is missing?
- what if looper config file is not found?
- what if the data file is not found, (path is wrong) and the pipeline fails?
- any other common mistake you could think

To test these, just mess up the file intentionally and then run `looper run`, and see what the error message is. You probably just need to do a better job catching errors and giving better messages in these common cases.

**Comment by nsheff** [comment]
here's an error I'm getting if the pipeline interface is malformed:


```
Using looper config (.looper.yaml).
Traceback (most recent call last):
  File "/home/nsheff/.local/bin/looper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/cli_pydantic.py", line 352, in main
    return run_looper(args, parser, test_args=test_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/cli_pydantic.py", line 201, in run_looper
    p = Project(
        ^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/project.py", line 142, in __init__
    self._samples_by_interface = self._samples_by_piface(self.piface_key)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/project.py", line 687, in _samples_by_piface
    PipelineInterface(
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/pipeline_interface.py", line 59, in __init__
    self._expand_paths(["compute", "dynamic_variables_script_path"])
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/pipeline_interface.py", line 321, in _expand_paths
    raw_path = _get_from_dict(self, keys)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nsheff/.local/lib/python3.12/site-packages/looper/pipeline_interface.py", line 299, in _get_from_dict
    map = map[a]
          ~~~^^^
TypeError: string indices must be integers, not 'str'

```

**Comment by donaldcampbelljr** [comment]
Currently if the pipeline interface is malformed or the path doesn't exist looper marks it as so:

```console
1 unique reasons for submission failure: No pipeline interfaces defined

Summary of failures:
No pipeline interfaces defined: frog_1, frog_2
```

Should we change this to more specifically state that it could not find the given interface and show the user provided path?

**Comment by donaldcampbelljr** [comment]
I've added better warnings for certain scenarios regarding looper config, pifaces, and PEPs.
