### ISSUE TITLE
looper report file location parameter missing

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#534]
I cannot find out how to change the output file location for looper report. Is it just missing from the CLI docs?

In this case, I need it to somewhere other than the default:

```
looper report --portable
Looper version: 2.0.0a2
Command: report
Using looper config (.looper.yaml).
No config key in Project, or reading project from dict
Portable flag set: True
Building index page for pipeline: PEPATAC
Creating objects summary
'PEPATAC' pipeline stats summary (n=1): /project/shefflab/brickyard/results_pipeline/tlgl_atac/PEPATAC_stats_summary.tsv
'PEPATAC' pipeline objects summary (n=0): /project/shefflab/brickyard/results_pipeline/tlgl_atac/PEPATAC_objs_summary.yaml
 * Creating sample pages
 * Creating object pages
Traceback (most recent call last):
  File "/sfs/applications/202406_build/software/standard/core/miniforge/24.3.0-py3.11/lib/python3.11/shutil.py", line 1018, in _make_zipfile
    zf.write(path, arcname)
  File "/sfs/applications/202406_build/software/standard/core/miniforge/24.3.0-py3.11/lib/python3.11/zipfile.py", line 1793, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
  File "/sfs/applications/202406_build/software/standard/core/miniforge/24.3.0-py3.11/lib/python3.11/zipfile.py", line 1207, in close
    self._fileobj.seek(self._zinfo.header_offset)
OSError: [Errno 122] Disk quota exceeded
```

**Comment by nsheff** [comment]
Also, I"m not sure if this is a separate or what the problem is: but actually my disk quota should not be exceeded... so I"m not sure why it's giving that error. 

That might not be a looper issue, I'll have to troubleshoot.

**Comment by donaldcampbelljr** [comment]
This has been added to a development branch and will be merged to dev shortly.
