### ISSUE TITLE
looper summarize fails if sample protocol has no pipeline mapping

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/looper#56]
While `looper run` correctly skips samples with no pipeline mapping for their protocol, `looper summarize` raises an error:

```none
Traceback (most recent call last):
  File "/scratch/users/arendeiro/anaconda2/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/scratch/users/arendeiro/anaconda2/lib/python2.7/site-packages/looper/looper.py", line 863, in main
    Summarizer(prj)()
  File "/scratch/users/arendeiro/anaconda2/lib/python2.7/site-packages/looper/looper.py", line 652, in __call__
    ifaces = self.prj.interfaces_by_protocol[alpha_cased(protocol)]
  File "/scratch/users/arendeiro/anaconda2/lib/python2.7/site-packages/peppy/attribute_dict.py", line 163, in __getitem__
    raise KeyError(item)
KeyError: 'WGS'
```
I assume the expected behaviour would be for these samples to just be ignored, and summarize be allowed to finish, correct?

**Comment by nsheff** [comment]
yes, it should clearly work like you suggest.

**Comment by vreuter** [comment]
#45

**Comment by nsheff** [comment]
@vreuter did that commit also resolve this issue?

**Comment by vreuter** [comment]
Yes. There have been some changes since then, though, so please reopen if this recurs.
