### ISSUE TITLE
Looper summarize fails if pipeline does not specify summarizers

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/looper#57]
[This line](https://github.com/pepkit/looper/blob/master/looper/looper.py#L657) tries to make a set out of possible summarizers specified in the pipeline interfaces.
The issue is, if none is found, `None` is retrieved and this raises an error since a set has to be made out of a iterable:

```none
Traceback (most recent call last):
  File "/scratch/users/arendeiro/anaconda2/bin/looper", line 11, in <module>
    sys.exit(main())
  File "/scratch/users/arendeiro/anaconda2/lib/python2.7/site-packages/looper/looper.py", line 863, in main
    Summarizer(prj)()
  File "/scratch/users/arendeiro/anaconda2/lib/python2.7/site-packages/looper/looper.py", line 657, in __call__
    for summarizer in set(summarizers):
TypeError: 'NoneType' object is not iterable
```

**Comment by vreuter** [comment]
@afrendeiro do you know which version this happened with? I think it should be addressed now with https://github.com/pepkit/looper/commit/0d3da112cdf3f404240bd0c130d2426e06322b83 from @jpsmith5

**Comment by nsheff** [comment]
that is correct, I believe @jpsmith5 did address this, now that you mention it.
