### ISSUE TITLE
Duplicate sample name cli argument/variable

### ISSUE THREAD

**Issue by afrendeiro** [pepkit/looper#58]
There seems to be a discrepancy causing an error when there are duplicate sample names:
the CLI parser gives "[--allow-duplicate-names](https://github.com/pepkit/looper/blob/master/looper/looper.py#L115)" but later a "[ignore_duplicate_names](https://github.com/pepkit/looper/blob/master/looper/looper.py#L450)" variable is expected withing the arg namespace.

**Comment by nsheff** [comment]
I think this manifest to me as this error:
```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    load_entry_point('looper==0.9.1', 'console_scripts', 'looper')()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 853, in main
    run(args, remaining_args)
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 450, in __call__
    if args.ignore_duplicate_names:
AttributeError: 'Namespace' object has no attribute 'ignore_duplicate_names'
```
