### ISSUE TITLE
looper summarize cryptic error message

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#78]
```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 11, in <module>
    load_entry_point('looper==0.9.2', 'console_scripts', 'looper')()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 875, in main
    Summarizer(prj)()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/looper.py", line 680, in __call__
    report_path = report_builder(objs, stats, uniqify(columns))
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/html_reports.py", line 1603, in __call__
    index_html_path = create_index_html(objs, stats, columns)
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/html_reports.py", line 1590, in create_index_html
    prj_objs = create_project_objects()
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/looper/html_reports.py", line 1403, in create_project_objects
    ifaces = self.prj.interfaces_by_protocol[alpha_cased(protocol)]
  File "/sfs/lustre/scratch/ns5bc/.local/lib/python2.7/site-packages/peppy/attribute_dict.py", line 163, in __getitem__
    raise KeyError(item)
KeyError: 'RRBS'
```

I think this may happen when the pipeline interface is bad. Indeed, there's a note way up above that says: `Ignoring nonexistent pipeline interface location:...`

but then it gives this non-understandable error.

**Comment by nsheff** [comment]
do you by chance have easy access to the error message it now writes when there's no pipeline interface implementing the given protocol?

**Comment by vreuter** [comment]
```
looper:297 (__call__) [INFO] > ## [19 of 20] WGBS_human_1 (WGBS) 
looper:325 (__call__) [WARNING] > > Not submitted: No pipeline for protocol 
looper:297 (__call__) [INFO] > ## [20 of 20] WGBS_human_2 (WGBS) 
looper:325 (__call__) [WARNING] > > Not submitted: No pipeline for protocol 
looper:368 (__call__) [INFO] > 
Looper finished 
looper:370 (__call__) [INFO] > Samples valid for job generation: 0 of 20 
looper:372 (__call__) [INFO] > Successful samples: 0 of 20 
looper:374 (__call__) [INFO] > Commands submitted: 0 of 0 
looper:375 (__call__) [INFO] > Jobs submitted: 0 
looper:377 (__call__) [INFO] > Dry run. No jobs were actually submitted. 
looper:406 (__call__) [INFO] > 
1 unique reasons for submission failure: No pipeline for protocol 
looper:410 (__call__) [INFO] > 
Summary of failures:
No pipeline for protocol: SMART-seq_human_truseq_SE, Amplicon_human, ATAC-seq_human_PE, ChIP-seq_human_H3K27ac_PE, WGBS_human_1, Quant-seq_human, ATAC-seq_human_SE, ChIP-seq_human_CTCF_SE, ChIPmentation_human_H3K27ac_SE, Drop-seq_mouse, ChIPmentation_human_CTCF_SE, Drop-seq_human, RRBS_human_PE, RRBS_human, ChIPmentation_human_CTCF_PE, ChIPmentation_human_H3K27ac_PE, SMART-seq_human_SE, WGBS_human_2, ChIP-seq_human_CTCF_PE, ChIP-seq_human_H3K27ac_SE 
```

**Comment by vreuter** [comment]
`summarize` doesn't seem meaningful in a contrived context (perhaps previous errors/warnings are now preempted by the missing objects file condition), but here's the end snippet:
```
looper:469 (__call__) [INFO] > ## [19 of 20] WGBS_human_1 (WGBS) 
looper:475 (__call__) [WARNING] > No objects file '/home/vpr9v/microtest/results_pipeline/WGBS_human_1/objects.tsv' 
looper:469 (__call__) [INFO] > ## [20 of 20] WGBS_human_2 (WGBS) 
looper:475 (__call__) [WARNING] > No objects file '/home/vpr9v/microtest/results_pipeline/WGBS_human_2/objects.tsv' 
```

**Comment by nsheff** [comment]
the error came up during `summarize` though. I'm not sure what you mean. anyway, feel free to close and I'll re-open if I notice it again.  I think it came up when you run `looper summarize` but there's no existant pipeline interface.
